### ISSUE TITLE
As a user I want to find vegan restaurants in my area

### ISSUE THREAD

**Issue by yjlmotley** [4GeeksAcademy/miami61-yummy-vegan-food#3]
## ACCEPTANCE CRITERIAS

- [x] I can in put my city in the input and it will give me vegan restaurants near me
- [x] Connect the restaurant to the google maps link

**Comment by yjlmotley** [comment]
[2024021518375.pdf](https://github.com/4GeeksAcademy/miami61-yummy-vegan-food/files/14782033/2024021518375.pdf)

**Comment by Jaemarlee** [comment]
Done and done!!!
